const fs = require('fs');
const glob = require('glob');
const path = require('path');

// Support both 'mixers' array (Prismix style) and 'app' object (original style)
const configPath = path.join(process.cwd(), 'prisma/prismerge.json');
let config = {};

try {
  const fileContent = fs.readFileSync(configPath, 'utf8');
  const rawConfig = JSON.parse(fileContent);
  
  if (rawConfig.app) {
    config = {
      inputs: rawConfig.app.inputs,
      output: rawConfig.app.output,
      fragments: rawConfig.app.fragments
    };
  } else if (rawConfig.mixers && rawConfig.mixers.length > 0) {
    config = {
      inputs: rawConfig.mixers[0].inputs || rawConfig.mixers[0].input,
      output: rawConfig.mixers[0].output,
      fragments: (rawConfig.fragments || []).reduce((acc, f) => {
        acc[f.name || f.path] = f.path;
        return acc;
      }, {})
    };
  }
} catch (e) {
  console.error('Failed to read config from prisma/prismerge.json', e);
  process.exit(1);
}

function readFragment(name) {
  const filePath = config.fragments[name] || Object.values(config.fragments)[0]; // Fallback if name mismatch but only one fragment exists
  if (!filePath) return '';
  return fs.readFileSync(path.join(process.cwd(), filePath), 'utf8').trim();
}

const boilerplate = readFragment('boilerplate');

let mergedContent = '// *** GENERATED BY BUREAUOS PRISMERGE ENGINE :: DO NOT EDIT ***\n';

const inputFiles = [];
config.inputs.forEach(input => {
  const files = glob.sync(input);
  inputFiles.push(...files);
});

// Avoid duplicates
const uniqueFiles = [...new Set(inputFiles)];

uniqueFiles.forEach(file => {
  let content = fs.readFileSync(file, 'utf8');
  
  // Clean up content (remove generator/datasource if not standard base.prisma)
  if (!file.includes('base.prisma')) {
    content = content.replace(/generator\s+client\s+{[^}]*}/g, '');
    content = content.replace(/datasource\s+db\s+{[^}]*}/g, '');
  }
  
  // Replace fragments
  content = content.replace(/\.\.\.boilerplate/g, boilerplate);
  
  mergedContent += `\n// FROM: ${file}\n` + content + '\n';
});

fs.writeFileSync(config.output, mergedContent);
console.log(`Successfully merged ${uniqueFiles.length} files into ${config.output}`);
